source 'http://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'selenium-webdriver'
gem 'bundler'
gem 'rake'
gem 'appium_lib'
gem 'activesupport'
gem 'syntax'
gem 'rest-client'
gem 'mobpage', git: 'https://github.com/m-davalos/mobpage'
gem 'sauce_whisk'
gem 'mobmanager', git: 'https://github.com/m-davalos/mobmanager'